// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VKVideoReviews.DA.Context;

#nullable disable

namespace VKVideoReviews.DA.Migrations
{
    [DbContext(typeof(VkVideoReviewsDbContext))]
    partial class VkVideoReviewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VKVideoReviews.DA.Entities.FavoriteEntity", b =>
                {
                    b.Property<Guid>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("FavoriteId");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique();

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.GenreEntity", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GenreId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.GenresVideosEntity", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("GenreId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("GenresVideos");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.ReviewEntity", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewId");

                    b.HasIndex("Rate");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rate", "\"Rate\" >= 1 AND \"Rate\" <= 10");
                        });
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.UserAppSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("RefreshTokenHash")
                        .HasDatabaseName("IX_UserAppSessions_RefreshTokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAppSessions_UserId");

                    b.ToTable("UserAppSessions");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("VkUserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("VkUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.UserTokenEntity", b =>
                {
                    b.Property<Guid>("TokenRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("VkUserId")
                        .HasColumnType("bigint");

                    b.HasKey("TokenRecordId");

                    b.HasIndex("AccessTokenExpiresAt")
                        .HasDatabaseName("IX_UserTokens_ExpiresAt");

                    b.HasIndex("RefreshToken")
                        .HasDatabaseName("IX_UserTokens_RefreshToken");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VkUserId")
                        .HasDatabaseName("IX_UserTokens_VkUserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.VideoEntity", b =>
                {
                    b.Property<Guid>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("VideoTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VideoId");

                    b.HasIndex("VideoTypeId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.VideoTypeEntity", b =>
                {
                    b.Property<Guid>("VideoTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("VideoTypeId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("VideoTypes");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.FavoriteEntity", b =>
                {
                    b.HasOne("VKVideoReviews.DA.Entities.UserEntity", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VKVideoReviews.DA.Entities.VideoEntity", "Video")
                        .WithMany("Favorites")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.GenresVideosEntity", b =>
                {
                    b.HasOne("VKVideoReviews.DA.Entities.GenreEntity", "Genre")
                        .WithMany("GenresVideos")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VKVideoReviews.DA.Entities.VideoEntity", "Video")
                        .WithMany("GenresVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.ReviewEntity", b =>
                {
                    b.HasOne("VKVideoReviews.DA.Entities.UserEntity", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VKVideoReviews.DA.Entities.VideoEntity", "Video")
                        .WithMany("Reviews")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.UserAppSessionEntity", b =>
                {
                    b.HasOne("VKVideoReviews.DA.Entities.UserEntity", "User")
                        .WithMany("AppSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.UserTokenEntity", b =>
                {
                    b.HasOne("VKVideoReviews.DA.Entities.UserEntity", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.VideoEntity", b =>
                {
                    b.HasOne("VKVideoReviews.DA.Entities.VideoTypeEntity", "VideoType")
                        .WithMany("Videos")
                        .HasForeignKey("VideoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VideoType");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.GenreEntity", b =>
                {
                    b.Navigation("GenresVideos");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.UserEntity", b =>
                {
                    b.Navigation("AppSessions");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.VideoEntity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("GenresVideos");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VKVideoReviews.DA.Entities.VideoTypeEntity", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
